import { Property } from "@/types/property";

const properties: Property[] = [
  {
    _id:          "p7",
    slug:         "balcones-de-san-carlos",
    headline:     "Un apartamento que rinde como uno mucho más grande.",
    title:        "Balcones de San Carlos",
    excerpt:      "En el corazón de Lijacá, este apartamento de 67 m² en el piso 12 reúne tres habitaciones, un estudio independiente y una luz natural que acompaña cada rincón durante todo el día. Una distribución que, sin ser el apartamento más grande, se siente como uno.",
    description:  "La zona social integra sala y comedor bajo un cálido techo en madera, con un ventanal de piso a techo que llena el espacio de luz durante todo el día. La cocina integral y semicerrada facilita el día a día, mientras que el estudio independiente —ideal para teletrabajo— se suma a las tres habitaciones sin sacrificar espacio ni privacidad. Ubicado en la Torre 2 del conjunto Balcones de San Carlos, incluye parqueadero cubierto propio y acceso a gimnasio, salón comunal y parque infantil, todo con portería y recepción las 24 horas. Una oportunidad lista para habitar, sin obra ni remodelación pendiente, en uno de los sectores más consolidados del norte de Bogotá.",
    highlights:   ["67 m² privados en piso 12", "3 habitaciones + estudio independiente", "2 baños completos", "Parqueadero cubierto propio (No. 310)", "Sala y comedor integrados con techos en madera", "Cocina integral semicerrada", "Conjunto con gimnasio, salón comunal y parque infantil", "Portería con recepción 24 horas", "Listo para habitar, sin remodelación"],
    zoneText:     "Lijacá es uno de los barrios más consolidados de Usaquén, al norte de Bogotá, con fácil acceso a la Autopista Norte y la Carrera 7. Vivir aquí significa tener cerca colegios, comercio y servicios de salud, en un entorno residencial tranquilo y con alta estabilidad de valorización — una de las razones por las que comprar en esta zona sigue siendo una inversión segura en el tiempo.",
    status:       "venta",
    type:         "apartamento",
    zone:         "bogota",
    neighborhood: "Lijacá",
    city:         "Bogotá",
    area:         "67 m²",
    bedrooms:     3,
    bathrooms:    2,
    parking:      1,
    floor:        12,
    price:        345000000,
    priceDisplay: "$345.000.000",
    images: [
      { url: "/images/properties/balcones-san-carlos/01.webp", alt: "Sala — Balcones de San Carlos", width: 900, height: 1200, isPrimary: true },
      { url: "/images/properties/balcones-san-carlos/02.webp", alt: "Comedor — Balcones de San Carlos", width: 900, height: 1200 },
      { url: "/images/properties/balcones-san-carlos/03.webp", alt: "Cocina integral — Balcones de San Carlos", width: 900, height: 1200 },
      { url: "/images/properties/balcones-san-carlos/04.webp", alt: "Habitación principal — Balcones de San Carlos", width: 898, height: 1200 },
      { url: "/images/properties/balcones-san-carlos/05.webp", alt: "Habitación 2 — Balcones de San Carlos", width: 900, height: 1200 },
      { url: "/images/properties/balcones-san-carlos/06.webp", alt: "Habitación 3 — Balcones de San Carlos", width: 900, height: 1200 },
      { url: "/images/properties/balcones-san-carlos/07.webp", alt: "Estudio independiente — Balcones de San Carlos", width: 900, height: 1200 },
      { url: "/images/properties/balcones-san-carlos/08.webp", alt: "Baño principal — Balcones de San Carlos", width: 900, height: 1200 },
      { url: "/images/properties/balcones-san-carlos/09.webp", alt: "Segundo baño — Balcones de San Carlos", width: 900, height: 1200 },
      { url: "/images/properties/balcones-san-carlos/10.webp", alt: "Acceso apartamento 1210 — Balcones de San Carlos", width: 900, height: 1200 },
      { url: "/images/properties/balcones-san-carlos/11.webp", alt: "Fachada Torre 2 — Balcones de San Carlos", width: 900, height: 1200 },
      { url: "/images/properties/balcones-san-carlos/12.webp", alt: "Gimnasio del conjunto — Balcones de San Carlos", width: 900, height: 1200 },
      { url: "/images/properties/balcones-san-carlos/13.webp", alt: "Parque infantil — Balcones de San Carlos", width: 900, height: 1200 },
      { url: "/images/properties/balcones-san-carlos/14.webp", alt: "Salón comunal — Balcones de San Carlos", width: 900, height: 1200 },
      { url: "/images/properties/balcones-san-carlos/15.webp", alt: "Recepción — Balcones de San Carlos", width: 900, height: 1200 },
      { url: "/images/properties/balcones-san-carlos/16.webp", alt: "Parqueadero cubierto — Balcones de San Carlos", width: 900, height: 1200 },
    ],
    featured: true, featuredOrder: 0, isNew: true, investment: true,
    acmSelection: true,
    tags: ["usaquen", "bogota", "lijaca", "nuevo", "tres-habitaciones", "inversion"],
    publishedAt: "2026-09-12T10:00:00Z", updatedAt: "2026-09-12T10:00:00Z",
  },
  {
    _id:          "p8",
    slug:         "caminos-del-norte",
    headline:     "Tu próximo hogar, con vista abierta hacia la ciudad.",
    title:        "Caminos del Norte",
    excerpt:      "En Tibabita, al norte de Bogotá, este apartamento de 49 m² en el piso 8 se abre hacia un ventanal de piso a techo con vista despejada a la ciudad. Una propuesta funcional y luminosa, con toda su documentación —apartamento y parqueadero— completamente independiente.",
    description:  "El área social se integra directamente con una cocina completamente equipada, mientras que las dos habitaciones cuentan con ventana propia, buena entrada de luz y clósets funcionales. El baño completo y la zona de ropas independiente, con lavadero y calentador propio, resuelven el día a día sin complicaciones. El conjunto suma piscina cubierta, gimnasio, salón comunal, parque infantil, cancha múltiple y vigilancia las 24 horas, todo dentro de una administración de $380.000. Ubicado a minutos del Portal del Norte, la Terminal del Norte y el Centro Comercial Santa Fe, es una excelente alternativa tanto para vivir como para invertir en el norte de la ciudad.",
    highlights:   ["49 m² en piso 8, con ascensor", "2 habitaciones con clóset y ventana propia", "1 baño completo", "Parqueadero cubierto independiente", "Cocina integral equipada", "Zona de ropas con lavadero y calentador propio", "Documentación de apartamento y parqueadero separadas", "Piscina cubierta, gimnasio y cancha múltiple", "Vigilancia 24 horas"],
    zoneText:     "Tibabita, en la localidad de Usaquén, es un sector estratégico al norte de Bogotá con conexión inmediata por la Calle 191, la Carrera 7, la Carrera 9 y la Autopista Norte. Su cercanía al Portal del Norte, la Terminal del Norte, el Centro Comercial Santa Fe y Colsubsidio lo convierte en un punto de fácil movilidad, ideal tanto para quienes buscan vivienda como para quienes buscan una inversión con buena proyección de arriendo.",
    status:       "venta",
    type:         "apartamento",
    zone:         "bogota",
    neighborhood: "Tibabita",
    city:         "Bogotá",
    area:         "49 m²",
    bedrooms:     2,
    bathrooms:    1,
    parking:      1,
    floor:        8,
    price:        235500000,
    priceDisplay: "$235.500.000",
    images: [
      { url: "/images/properties/caminos-del-norte/01.webp", alt: "Área social — Caminos del Norte", width: 900, height: 1200, isPrimary: true },
      { url: "/images/properties/caminos-del-norte/02.webp", alt: "Cocina integral — Caminos del Norte", width: 1200, height: 900 },
      { url: "/images/properties/caminos-del-norte/03.webp", alt: "Habitación 1 — Caminos del Norte", width: 1200, height: 900 },
      { url: "/images/properties/caminos-del-norte/04.webp", alt: "Habitación 1, detalle — Caminos del Norte", width: 1200, height: 900 },
      { url: "/images/properties/caminos-del-norte/05.webp", alt: "Habitación 2 — Caminos del Norte", width: 1200, height: 900 },
      { url: "/images/properties/caminos-del-norte/06.webp", alt: "Circulación — Caminos del Norte", width: 1200, height: 900 },
      { url: "/images/properties/caminos-del-norte/07.webp", alt: "Baño — Caminos del Norte", width: 1200, height: 900 },
      { url: "/images/properties/caminos-del-norte/08.webp", alt: "Baño, vista — Caminos del Norte", width: 900, height: 1200 },
      { url: "/images/properties/caminos-del-norte/09.webp", alt: "Zona de ropas — Caminos del Norte", width: 1200, height: 900 },
      { url: "/images/properties/caminos-del-norte/10.webp", alt: "Piscina cubierta — Caminos del Norte", width: 1200, height: 675 },
      { url: "/images/properties/caminos-del-norte/11.webp", alt: "Parqueadero y cancha múltiple — Caminos del Norte", width: 1200, height: 675 },
      { url: "/images/properties/caminos-del-norte/12.webp", alt: "Parque infantil — Caminos del Norte", width: 1200, height: 675 },
    ],
    featured: true, featuredOrder: 0.5, isNew: true, investment: true,
    acmSelection: true,
    tags: ["usaquen", "bogota", "tibabita", "nuevo", "primera-vivienda", "inversion"],
    publishedAt: "2026-09-12T09:00:00Z", updatedAt: "2026-09-12T09:00:00Z",
  },
  {
    _id:          "p1",
    slug:         "alameda-san-antonio",
    headline:     "Un hogar pensado para comenzar una nueva etapa.",
    title:        "Alameda San Antonio II",
    excerpt:      "Hay viviendas que simplemente cumplen una función, y otras que invitan a imaginar la vida que puede construirse dentro de ellas. Este apartamento de 67 m² en Usaquén pertenece a ese segundo grupo.",
    description:  "La luz natural acompaña los espacios sociales durante gran parte del día gracias a sus amplios ventanales, mientras que la distribución separa de forma inteligente las zonas privadas de las áreas comunes. La cocina independiente, conectada con la zona de lavandería, facilita el día a día sin interferir con los espacios de descanso. Los acabados en madera aportan calidez y permiten adaptar fácilmente cada ambiente al estilo de quienes lo habiten. Ubicado en uno de los sectores con mayor consolidación del norte de Bogotá, representa una excelente oportunidad para quienes buscan comprar su primera vivienda o realizar una inversión con potencial de valorización.",
    highlights:   ["67 m² de excelente distribución", "3 habitaciones", "2 baños", "Excelente iluminación natural", "Cocina independiente", "Zona de lavandería", "Ideal para familias"],
    zoneText:     "Usaquén se ha consolidado como uno de los sectores residenciales más atractivos de Bogotá gracias a su equilibrio entre tranquilidad, comercio, gastronomía y conectividad. Vivir aquí significa tener acceso a centros comerciales, parques, colegios, servicios y múltiples vías principales sin renunciar a un entorno residencial agradable.",
    status:       "reservado",
    type:         "apartamento",
    zone:         "bogota",
    neighborhood: "Usaquén",
    city:         "Bogotá",
    area:         "67 m²",
    bedrooms:     3,
    bathrooms:    2,
    parking:      0,
    price:        334000000,
    priceDisplay: "$334.000.000",
    images: [
      { url: "/images/properties/alameda-san-antonio/01.webp", alt: "Sala — Alameda San Antonio II", width: 1200, height: 900, isPrimary: true },
      { url: "/images/properties/alameda-san-antonio/02.webp", alt: "Habitación — Alameda San Antonio II", width: 1200, height: 900 },
      { url: "/images/properties/alameda-san-antonio/03.webp", alt: "Cocina — Alameda San Antonio II", width: 1200, height: 900 },
      { url: "/images/properties/alameda-san-antonio/04.webp", alt: "Baño — Alameda San Antonio II", width: 1200, height: 900 },
    ],
    featured: true, featuredOrder: 1, investment: false,
    acmSelection: false,
    tags: ["usaquen", "bogota", "primera-vivienda", "familias"],
    publishedAt: "2025-06-01T00:00:00Z", updatedAt: "2025-06-01T00:00:00Z",
  },
  {
    _id:          "p2",
    slug:         "altos-san-jorge",
    headline:     "Una excelente oportunidad para vivir o invertir.",
    title:        "Altos de San Jorge",
    excerpt:      "Cada metro cuadrado de este apartamento ha sido diseñado para aprovechar al máximo la luz y la funcionalidad. Con 56 m², dos habitaciones y parqueadero privado, ofrece una distribución eficiente que responde perfectamente a las necesidades de parejas, familias pequeñas o personas que buscan independizarse.",
    description:  "Su zona social recibe abundante iluminación gracias a un amplio ventanal que además permite disfrutar de una vista abierta sobre la ciudad, aportando una agradable sensación de amplitud durante todo el día. La cocina integrada favorece un estilo de vida moderno y práctico, mientras que los acabados neutros permiten personalizar fácilmente cada espacio. Una alternativa muy atractiva para quienes buscan comprar vivienda en Suba con excelente relación entre precio, ubicación y proyección de valorización.",
    highlights:   ["56 m²", "2 habitaciones", "Parqueadero privado", "Vista panorámica", "Excelente iluminación", "Cocina integrada"],
    zoneText:     "Suba es una de las localidades con mayor crecimiento residencial de Bogotá. Cuenta con una amplia oferta de transporte, comercio, zonas verdes y servicios, convirtiéndose en una excelente alternativa tanto para vivir como para invertir en vivienda.",
    status:       "vendido",
    type:         "apartamento",
    zone:         "bogota",
    neighborhood: "Suba",
    city:         "Bogotá",
    area:         "56 m²",
    bedrooms:     2,
    bathrooms:    1,
    parking:      1,
    price:        309000000,
    priceDisplay: "$309.000.000",
    images: [
      { url: "/images/properties/altos-san-jorge/01.webp", alt: "Sala — Altos de San Jorge", width: 1200, height: 900, isPrimary: true },
      { url: "/images/properties/altos-san-jorge/02.webp", alt: "Baño — Altos de San Jorge", width: 1200, height: 900 },
      { url: "/images/properties/altos-san-jorge/03.webp", alt: "Habitación — Altos de San Jorge", width: 1200, height: 900 },
      { url: "/images/properties/altos-san-jorge/04.webp", alt: "Cocina — Altos de San Jorge", width: 1200, height: 900 },
    ],
    featured: true, featuredOrder: 2, investment: true,
    acmSelection: true,
    tags: ["suba", "bogota", "inversion", "parejas"],
    publishedAt: "2025-06-05T00:00:00Z", updatedAt: "2025-06-05T00:00:00Z",
  },
  {
    _id:          "p3",
    slug:         "viantt-cajica",
    headline:     "La tranquilidad de la Sabana con la comodidad de una vivienda contemporánea.",
    title:        "Viantt Apartamentos",
    excerpt:      "Este apartamento combina funcionalidad, diseño moderno y una ubicación estratégica para quienes desean disfrutar de un entorno más tranquilo sin alejarse de Bogotá.",
    description:  "Sus 46 m² están distribuidos de manera inteligente para ofrecer dos habitaciones, dos baños completos y una agradable zona social iluminada naturalmente. El área de sala conecta con un balcón francés que aporta ventilación y una mayor sensación de amplitud, mientras que la cocina moderna incorpora acabados claros y una distribución pensada para el uso diario. Una propiedad ideal tanto para primera vivienda como para quienes desean invertir en una de las zonas con mayor crecimiento de la Sabana de Bogotá.",
    highlights:   ["46 m²", "2 habitaciones", "2 baños completos", "Parqueadero privado", "Diseño contemporáneo", "Excelente iluminación"],
    zoneText:     "Cajicá se ha convertido en uno de los municipios con mayor desarrollo urbanístico de Cundinamarca gracias a su calidad de vida, tranquilidad y cercanía con Bogotá. Su crecimiento constante ha impulsado la valorización de la vivienda y la convierte en una excelente opción para vivir o invertir.",
    status:       "venta",
    type:         "apartamento",
    zone:         "cajica",
    neighborhood: "Cajicá",
    city:         "Cajicá",
    area:         "46 m²",
    bedrooms:     2,
    bathrooms:    2,
    parking:      1,
    price:        322000000,
    priceDisplay: "$322.000.000",
    images: [
      { url: "/images/properties/viantt/01.webp", alt: "Sala — Viantt Cajicá", width: 1200, height: 900, isPrimary: true },
      { url: "/images/properties/viantt/02.webp", alt: "Habitación — Viantt Cajicá", width: 1200, height: 900 },
      { url: "/images/properties/viantt/03.webp", alt: "Baño — Viantt Cajicá", width: 1200, height: 900 },
      { url: "/images/properties/viantt/04.webp", alt: "Cocina — Viantt Cajicá", width: 1200, height: 900 },
    ],
    featured: true, featuredOrder: 3, investment: true,
    acmSelection: false,
    tags: ["cajica", "sabana", "inversion", "tranquilidad"],
    publishedAt: "2025-06-10T00:00:00Z", updatedAt: "2025-06-10T00:00:00Z",
  },
  {
    _id:          "p4",
    slug:         "san-simon-la-quinta",
    headline:     "Espacios amplios para disfrutar cada momento en familia.",
    title:        "San Simón La Quinta",
    excerpt:      "Este apartamento ofrece una distribución cómoda y funcional pensada para quienes buscan una vivienda lista para comenzar una nueva etapa.",
    description:  "Sus 67 m² integran tres habitaciones, dos baños completos y una moderna cocina abierta con barra en granito que conecta naturalmente con la zona social, generando un ambiente amplio y acogedor para compartir en familia. Los acabados contemporáneos, los amplios espacios de almacenamiento y la iluminación natural convierten esta propiedad en una excelente alternativa para quienes valoran el confort y la practicidad. Una oportunidad ideal para adquirir vivienda en una de las ciudades con mayor crecimiento residencial de Cundinamarca.",
    highlights:   ["67 m²", "3 habitaciones", "2 baños", "Parqueadero privado", "Cocina abierta con barra en granito", "Excelente distribución"],
    zoneText:     "Zipaquirá continúa posicionándose como uno de los municipios con mayor proyección de crecimiento gracias a su desarrollo urbano, su calidad de vida y su cercanía con Bogotá. Su infraestructura, oferta educativa y conectividad la convierten en un lugar ideal para establecer un hogar o realizar una inversión inmobiliaria.",
    status:       "venta",
    type:         "apartamento",
    zone:         "sabana",
    neighborhood: "Zipaquirá",
    city:         "Zipaquirá",
    area:         "67 m²",
    bedrooms:     3,
    bathrooms:    2,
    parking:      1,
    price:        309000000,
    priceDisplay: "$309.000.000",
    images: [
      { url: "/images/properties/san-simon/01.webp", alt: "Sala — San Simón La Quinta", width: 1200, height: 900, isPrimary: true },
      { url: "/images/properties/san-simon/02.webp", alt: "Cocina — San Simón La Quinta", width: 1200, height: 900 },
      { url: "/images/properties/san-simon/03.webp", alt: "Habitación — San Simón La Quinta", width: 1200, height: 900 },
      { url: "/images/properties/san-simon/04.webp", alt: "Baño — San Simón La Quinta", width: 1200, height: 900 },
    ],
    featured: false, featuredOrder: 4, investment: false,
    acmSelection: true,
    tags: ["zipaquira", "sabana", "familias", "primera-vivienda"],
    publishedAt: "2025-06-15T00:00:00Z", updatedAt: "2025-06-15T00:00:00Z",
  },
  {
    _id:          "p5",
    slug:         "valverde-olivo-chia",
    headline:     "Vivir rodeado de tranquilidad, sin alejarse de la ciudad.",
    title:        "Valverde Olivo",
    excerpt:      "Hay hogares que destacan por su tamaño y otros por la forma en que aprovechan cada espacio. Este apartamento de 50 m² en Chía ha sido diseñado para ofrecer una distribución eficiente, luminosa y cómoda.",
    description:  "Sus dos habitaciones y dos baños proporcionan el equilibrio perfecto entre funcionalidad y confort, mientras que la zona social se convierte en un espacio acogedor para compartir el día a día. La cocina, integrada de manera natural con el área social, favorece una sensación de amplitud y una vida más práctica. Ubicado en uno de los municipios con mayor crecimiento de la Sabana de Bogotá, Valverde Olivo representa una excelente oportunidad para quienes buscan calidad de vida, buena conectividad y una inversión respaldada por el desarrollo constante de la zona.",
    highlights:   ["50 m² con excelente aprovechamiento", "2 habitaciones", "2 baños completos", "Distribución moderna y funcional", "Excelente iluminación natural", "Ideal para parejas, familias o inversionistas"],
    zoneText:     "Chía se ha consolidado como uno de los municipios más atractivos para vivir e invertir en Cundinamarca. Su cercanía con Bogotá, la calidad de sus servicios, la oferta educativa, los centros comerciales y las amplias zonas verdes la convierten en un lugar ideal para quienes buscan una mejor calidad de vida.",
    status:       "venta",
    type:         "apartamento",
    zone:         "chia",
    neighborhood: "Chía",
    city:         "Chía",
    area:         "50 m²",
    bedrooms:     2,
    bathrooms:    2,
    parking:      0,
    price:        289000000,
    priceDisplay: "$289.000.000",
    images: [
      { url: "/images/properties/valverde-olivo/01.webp", alt: "Sala — Valverde Olivo Chía", width: 1200, height: 900, isPrimary: true },
      { url: "/images/properties/valverde-olivo/02.webp", alt: "Habitación — Valverde Olivo Chía", width: 1200, height: 900 },
      { url: "/images/properties/valverde-olivo/03.webp", alt: "Sala amplia — Valverde Olivo Chía", width: 1200, height: 900 },
      { url: "/images/properties/valverde-olivo/04.webp", alt: "Baño — Valverde Olivo Chía", width: 1200, height: 900 },
    ],
    featured: false, featuredOrder: 5, investment: true,
    acmSelection: true,
    tags: ["chia", "sabana", "inversion", "tranquilidad", "parejas"],
    publishedAt: "2025-06-20T00:00:00Z", updatedAt: "2025-06-20T00:00:00Z",
  },
];

export const getAllProperties      = ()               => [...properties].sort((a,b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime());
export const getFeaturedProperties = ()               => properties.filter(p => p.featured).sort((a,b) => (a.featuredOrder??99)-(b.featuredOrder??99));
export const getPropertyBySlug     = (slug: string)  => properties.find(p => p.slug === slug);
export const getInvestmentProperties = ()            => properties.filter(p => p.investment);
export const getACMSelection       = ()              => properties.filter(p => p.acmSelection);
export const getPropertiesByZone   = (zone: Property["zone"]) => properties.filter(p => p.zone === zone);
